import re
import json
from typing import Dict, List, Set

# Matches: import X from 'pkg', import 'pkg', from 'pkg' import X
_NPM_IMPORT_RE = re.compile(
    r"""(?:import|from)\s+['"](@?[a-zA-Z0-9][a-zA-Z0-9\-._]*(?:/[a-zA-Z0-9][a-zA-Z0-9\-._]*)*)['"]""",
    re.MULTILINE,
)

# Matches: import X, from X import Y (top-level only)
_PY_IMPORT_RE = re.compile(
    r"^(?:import\s+([\w.]+)|from\s+([\w.]+)\s+import)",
    re.MULTILINE,
)

_PYTHON_STDLIB = {
    "os", "sys", "re", "json", "datetime", "typing", "pathlib", "uuid",
    "hashlib", "hmac", "base64", "io", "time", "math", "random", "enum",
    "functools", "itertools", "collections", "contextlib", "asyncio",
    "logging", "traceback", "copy", "abc", "dataclasses", "warnings",
    "urllib", "http", "email", "string", "struct", "threading", "queue",
    "subprocess", "shutil", "tempfile", "glob", "fnmatch", "stat",
    "__future__", "builtins", "types", "inspect", "importlib", "decimal",
    "fractions", "statistics", "array", "heapq", "bisect", "weakref",
    "operator", "pprint", "textwrap", "unicodedata", "codecs", "csv",
    "configparser", "argparse", "getopt", "platform", "signal", "ctypes",
    "pickle", "shelve", "sqlite3", "zlib", "gzip", "bz2", "lzma", "zipfile",
    "tarfile", "socket", "ssl", "select", "selectors", "errno", "mimetypes",
    "html", "xml", "cgi", "cgitb", "wsgiref", "concurrent", "multiprocessing",
    "atexit", "gc", "weakref", "dis", "tokenize", "ast", "symtable",
    "token", "keyword", "codeop", "linecache", "site", "sysconfig",
    "distutils", "test", "unittest", "doctest", "pdb", "profile", "cProfile",
    "timeit", "trace", "sys", "typing_extensions",
    # Internal project package names generated by LLM — never pip packages
    "app", "api", "core", "models", "schemas", "routes", "routers", "services",
    "middleware", "config", "database", "security", "dependencies", "utils",
    "crud", "db", "auth", "handlers", "controllers", "repositories", "common",
}

# Node.js built-ins — never npm packages
_NODE_BUILTINS = {
    "path", "fs", "os", "crypto", "http", "https", "url", "util", "events",
    "stream", "buffer", "child_process", "cluster", "net", "tls", "dns",
    "readline", "repl", "vm", "module", "process", "timers", "assert",
    "constants", "domain", "string_decoder", "punycode", "querystring",
    "zlib", "v8", "perf_hooks", "worker_threads", "inspector",
}

# Internal path alias prefixes — not npm packages
_INTERNAL_PREFIXES = (".", "@/", "~/", "#")

# Python import name → pip package name (when they differ)
_PY_IMPORT_TO_PIP: Dict[str, str] = {
    "jose":            "python-jose",
    "passlib":         "passlib",
    "dotenv":          "python-dotenv",
    "motor":           "motor",
    "bson":            "pymongo",
    "pymongo":         "pymongo",
    "pydantic":        "pydantic",
    "fastapi":         "fastapi",
    "uvicorn":         "uvicorn",
    "starlette":       "starlette",
    "aiofiles":        "aiofiles",
    "PIL":             "Pillow",
    "cv2":             "opencv-python",
    "sklearn":         "scikit-learn",
    "bs4":             "beautifulsoup4",
    "yaml":            "PyYAML",
    "toml":            "toml",
    "httpx":           "httpx",
    "requests":        "requests",
    "email_validator": "email-validator",
    "multipart":       "python-multipart",
    "stripe":          "stripe",
    "boto3":           "boto3",
    "celery":          "celery",
    "redis":           "redis",
    "sendgrid":        "sendgrid",
    "jinja2":          "Jinja2",
    "cryptography":    "cryptography",
    "jwt":             "PyJWT",
    "bcrypt":          "bcrypt",
    "pydantic_settings": "pydantic-settings",
}


def _npm_package_name(import_path: str) -> str | None:
    """
    Extract the installable npm package name from an import path.

    '@hookform/resolvers/zod' → '@hookform/resolvers'
    '@radix-ui/react-dialog' → '@radix-ui/react-dialog'
    'react-hook-form'        → 'react-hook-form'
    './components/Foo'       → None  (relative)
    '@/services/api'         → None  (path alias)
    'path'                   → None  (Node.js built-in)
    """
    if not import_path:
        return None
    for prefix in _INTERNAL_PREFIXES:
        if import_path.startswith(prefix):
            return None
    if import_path.startswith("@"):
        parts = import_path.split("/")
        pkg = f"{parts[0]}/{parts[1]}" if len(parts) >= 2 else import_path
        # Filter out internal @/ aliases that slipped through
        if pkg.startswith("@/"):
            return None
        return pkg
    name = import_path.split("/")[0]
    if name in _NODE_BUILTINS:
        return None
    return name


def extract_npm_imports(content: str) -> Set[str]:
    """Return all npm package names imported in a TS/TSX file."""
    packages: Set[str] = set()
    for m in _NPM_IMPORT_RE.finditer(content):
        pkg = _npm_package_name(m.group(1))
        if pkg:
            packages.add(pkg)
    return packages


def extract_python_imports(content: str) -> Set[str]:
    """Return all third-party pip package names imported in a Python file."""
    packages: Set[str] = set()
    for m in _PY_IMPORT_RE.finditer(content):
        module = m.group(1) or m.group(2)
        if not module:
            continue
        top = module.split(".")[0]
        if top in _PYTHON_STDLIB:
            continue
        packages.add(_PY_IMPORT_TO_PIP.get(top, top))
    return packages


def _declared_npm(package_json_content: str) -> Set[str]:
    try:
        pkg = json.loads(package_json_content)
    except Exception:
        return set()
    declared: Set[str] = set()
    declared.update(pkg.get("dependencies", {}).keys())
    declared.update(pkg.get("devDependencies", {}).keys())
    return declared


def _declared_pip(requirements_content: str) -> Set[str]:
    declared: Set[str] = set()
    for line in requirements_content.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        pkg = re.split(r"[>=<!~\[\s]", line)[0].strip().lower()
        if pkg:
            declared.add(pkg)
    return declared


def scan_flat_files(flat_files: List[dict]) -> dict:
    """
    Scan a list of {"path": str, "content": str} dicts.

    Returns:
      {
        "npm_imports":   set of all npm packages found in TS/TSX files,
        "pip_imports":   set of all pip packages found in .py files,
        "npm_missing":   list of packages imported but not in package.json,
        "pip_missing":   list of packages imported but not in requirements.txt,
        "package_json_raw":    str | None,
        "requirements_raw":    str | None,
      }
    """
    npm_imports: Set[str] = set()
    pip_imports: Set[str] = set()
    package_json_raw: str | None = None
    requirements_raw: str | None = None

    for f in flat_files:
        path: str = f.get("path", "")
        content: str = f.get("content", "") or ""

        if path == "frontend/package.json":
            package_json_raw = content
        elif path == "backend/requirements.txt":
            requirements_raw = content
        elif path.startswith("frontend/") and path.endswith((".ts", ".tsx")):
            npm_imports.update(extract_npm_imports(content))
        elif path.startswith("backend/") and path.endswith(".py"):
            pip_imports.update(extract_python_imports(content))

    declared_npm = _declared_npm(package_json_raw or "{}")
    declared_pip = _declared_pip(requirements_raw or "")

    npm_missing = [p for p in npm_imports if p not in declared_npm]
    pip_missing = [p for p in pip_imports if p.lower() not in declared_pip]

    return {
        "npm_imports":       npm_imports,
        "pip_imports":       pip_imports,
        "npm_missing":       npm_missing,
        "pip_missing":       pip_missing,
        "package_json_raw":  package_json_raw,
        "requirements_raw":  requirements_raw,
    }
