import os
from typing import Optional

class DebuggerAgent:
    """Validates frontend-only projects generated by DeveloperAgent (HTML/CSS/JS)."""

    def __init__(self, verbose: bool = True):
        self.verbose = verbose

    def debug(self, html_file: str) -> bool:
        """
        Debug the project:
        - html_file: path to the generated HTML file
        Returns True if file exists and basic validation passes, False otherwise.
        """
        # Check if file exists
        if not os.path.exists(html_file):
            print(f"❌ HTML file not found: {html_file}")
            return False

        if self.verbose:
            print(f"📄 Found HTML file: {html_file}")

        try:
            # Basic validation: read file and check for <html> and <script> tags
            with open(html_file, "r", encoding="utf-8") as f:
                content = f.read()

            if "<html" not in content.lower() or "</html>" not in content.lower():
                print("❌ Invalid HTML: missing <html> or </html> tags.")
                return False

            if self.verbose:
                print("✅ Basic HTML structure found.")

            # Optional: Check if JS functions exist (simple heuristic)
            if "<script" in content.lower():
                if self.verbose:
                    print("✅ JavaScript detected in HTML file.")
            else:
                if self.verbose:
                    print("⚠️ No <script> tags detected. Interactivity may be missing.")

            return True

        except Exception as e:
            print(f"🚨 Unexpected error during debugging: {e}")
            return False
