class DebuggerAgent:
    """
    Validates multi-folder full-stack projects generated by DeveloperAgent.
    Performs STRUCTURAL validation only (no LLM).
    """

    REQUIRED_FRONTEND_FILES = {
        "frontend/src/main.tsx",
        "frontend/src/App.tsx",
    }

    REQUIRED_BACKEND_FILES = {
        "backend/main.py",
    }

    def __init__(self, verbose: bool = True) -> None:
        self.verbose = verbose

    def _collect_files(self, structure: list, base_path: str = "") -> set[str]:
        files: set[str] = set()

        for node in structure:
            current_path = f"{base_path}/{node['name']}".lstrip("/")

            if node["type"] == "file":
                files.add(current_path)

            elif node["type"] == "folder":
                files |= self._collect_files(node.get("children", []), current_path)

        return files

    def validate(self, project_json: dict) -> bool:
        if not project_json or "structure" not in project_json:
            print("❌ Invalid project JSON: missing 'structure'")
            return False

        all_files = self._collect_files(project_json["structure"])

        if self.verbose:
            print("📁 Files detected:")
            for f in sorted(all_files):
                print("  -", f)

        missing_frontend = self.REQUIRED_FRONTEND_FILES - all_files
        if missing_frontend:
            print("❌ Missing frontend files:", missing_frontend)
            return False

        missing_backend = self.REQUIRED_BACKEND_FILES - all_files
        if missing_backend:
            print("❌ Missing backend files:", missing_backend)
            return False

        if self.verbose:
            print("✅ Frontend structure valid (React + TSX)")
            print("✅ Backend structure valid (FastAPI)")
            print("✅ Project validation passed")

        return True
