import re
import ast
from pathlib import Path
from typing import Optional, Dict, List, Tuple, Any

from core.validation.import_extractor import extract_npm_imports, _NODE_BUILTINS, _INTERNAL_PREFIXES

class DebuggerAgent:
    """
    Validates and auto-fixes multi-folder full-stack projects generated by DeveloperAgent.
    Performs STRUCTURAL validation and auto-fixes common LLM mistakes (no LLM).
    Ensures 100% error-free project generation through comprehensive checks.
    """

    REQUIRED_FRONTEND_FILES = {
        "frontend/src/main.tsx",
        "frontend/src/App.tsx",
    }

    REQUIRED_BACKEND_FILES = {
        "backend/main.py",
    }

    def __init__(self, verbose: bool = True) -> None:
        self.verbose = verbose
        self.fixes_applied: List[str] = []
        self.errors_found: List[str] = []
        self.performance_metrics: Dict[str, Any] = {}
        self.security_issues: List[str] = []

    def _collect_files(self, structure: list, base_path: str = "") -> set[str]:
        files: set[str] = set()

        for node in structure:
            current_path = f"{base_path}/{node['name']}".lstrip("/")

            if node["type"] == "file":
                files.add(current_path)

            elif node["type"] == "folder":
                files |= self._collect_files(node.get("children", []), current_path)

        return files

    def validate(self, project_json: dict) -> bool:
        if not project_json or "structure" not in project_json:
            print("[Debugger] Invalid project JSON: missing 'structure'")
            return False

        all_files = self._collect_files(project_json["structure"])

        if self.verbose:
            print("[Debugger] Files detected:")
            for f in sorted(all_files):
                print("  -", f)

        missing_frontend = self.REQUIRED_FRONTEND_FILES - all_files
        if missing_frontend:
            print("[Debugger] Missing frontend files:", missing_frontend)
            return False

        missing_backend = self.REQUIRED_BACKEND_FILES - all_files
        if missing_backend:
            print("[Debugger] Missing backend files:", missing_backend)
            return False

        if self.verbose:
            print("[Debugger] Frontend structure valid (React + TSX)")
            print("[Debugger] Backend structure valid (FastAPI)")
            print("[Debugger] Project validation passed")

        return True

    def validate_backend_code(self, backend_path: Path) -> list:
        """
        Validate backend code. Structure-agnostic: works with flat, modular,
        and Express-style layouts. Reads each file exactly once.
        """
        errors = []
        try:
            req_file = backend_path / "requirements.txt"
            is_fastapi = False
            req_content = ""
            if req_file.exists():
                req_content = req_file.read_text(encoding="utf-8").lower()
                is_fastapi = "fastapi" in req_content
                for pkg in ["fastapi", "uvicorn", "bcrypt"]:
                    if pkg not in req_content:
                        errors.append(f"requirements.txt missing: {pkg}")

            # Single pass over all Python files — collect all checks together
            has_security = False
            main_content = ""
            for py_file in backend_path.rglob("*.py"):
                if "__pycache__" in str(py_file):
                    continue
                try:
                    content = py_file.read_text(encoding="utf-8", errors="replace")
                    rel = str(py_file.relative_to(backend_path)).replace("\\", "/")
                    c_lower = content.lower()

                    if py_file.name == "main.py" and not main_content:
                        main_content = content

                    if "bcrypt" in c_lower or "jwt" in c_lower:
                        has_security = True

                    if "__get_validators__" in content:
                        errors.append(f"{rel}: deprecated __get_validators__ — use __get_pydantic_core_schema__")
                    if "from passlib.context import CryptContext" in content:
                        errors.append(f"{rel}: uses passlib — replace with direct bcrypt import")
                except Exception:
                    pass

            if not list(backend_path.rglob("main.py")) and not list(backend_path.rglob("index.ts")):
                errors.append("No entry point found (main.py / index.ts)")

            if is_fastapi and main_content:
                if "CORSMiddleware" not in main_content:
                    errors.append("main.py missing CORSMiddleware")
                if "5959" not in main_content:
                    errors.append("main.py CORS missing port 5959")

            if is_fastapi and not has_security:
                errors.append("No security file found with bcrypt/JWT")

        except Exception as e:
            errors.append(f"Validation error: {str(e)}")

        return errors

    def validate_frontend_code(self, frontend_path: Path) -> list:
        """Validate frontend code and return list of errors found."""
        errors = []

        try:
            package_file = frontend_path / "package.json"
            if not package_file.exists():
                errors.append("Missing package.json")
            else:
                package_content = package_file.read_text(encoding="utf-8")
                for dep in ["react", "react-dom", "react-router-dom", "axios"]:
                    if dep not in package_content:
                        errors.append(f"Missing required dependency: {dep}")
                for dep in ["typescript", "vite", "@types/react"]:
                    if dep not in package_content:
                        errors.append(f"Missing required dev dependency: {dep}")

                # Scan TS/TSX imports with proper scoped-package handling
                imported_packages: set = set()
                for src_file in list(frontend_path.rglob("*.ts")) + list(frontend_path.rglob("*.tsx")):
                    if "node_modules" in str(src_file):
                        continue
                    try:
                        imported_packages.update(extract_npm_imports(src_file.read_text(encoding="utf-8")))
                    except Exception:
                        pass
                for pkg in imported_packages:
                    if pkg not in package_content:
                        errors.append(f"Missing dependency in package.json: {pkg}")

            vite_config = frontend_path / "vite.config.ts"
            if not vite_config.exists():
                errors.append("Missing vite.config.ts")
            else:
                vite_content = vite_config.read_text(encoding="utf-8")
                if "proxy:" not in vite_content:
                    errors.append("Missing proxy configuration in vite.config.ts")
                elif "7979" not in vite_content:
                    errors.append("Incorrect proxy target port (should be 7979)")

            # tsconfig.json: accept both flat and project-references styles
            tsconfig_file = frontend_path / "tsconfig.json"
            if not tsconfig_file.exists():
                errors.append("Missing tsconfig.json")

            if not (frontend_path / "index.html").exists():
                errors.append("Missing index.html")

            if not (frontend_path / "src" / "main.tsx").exists():
                errors.append("Missing src/main.tsx")

            app_file = frontend_path / "src" / "App.tsx"
            if not app_file.exists():
                errors.append("Missing src/App.tsx")
            else:
                app_content = app_file.read_text(encoding="utf-8")
                if "Route" not in app_content:
                    errors.append("App.tsx missing React Router Routes")

            # Check for class components (anti-pattern)
            components_dir = frontend_path / "src" / "components"
            if components_dir.exists():
                for comp_file in components_dir.rglob("*.tsx"):
                    try:
                        content = comp_file.read_text(encoding="utf-8")
                        if "extends React.Component" in content:
                            errors.append(f"Class component in {comp_file.relative_to(frontend_path)} — use functional components")
                    except Exception:
                        pass

        except Exception as e:
            errors.append(f"Validation error: {str(e)}")

        return errors

    def auto_fix_backend_file(self, content: str, rel_path: str) -> str:
        """Apply auto-fixes to backend file content."""
        original_content = content
        fixes_count = 0
        
        # Fix HTTP status code typos
        status_fixes = {
            "HTTP_24_NO_CONTENT": "HTTP_204_NO_CONTENT",
            "HTTP_20_OK": "HTTP_200_OK",
            "HTTP_20_CREATED": "HTTP_201_CREATED",
            "HTTP_40_NO_CONTENT": "HTTP_204_NO_CONTENT",
            "HTTP_404_NO": "HTTP_404_NOT_FOUND"
        }
        for wrong, correct in status_fixes.items():
            if wrong in content:
                content = content.replace(wrong, correct)
                fixes_count += 1
        
        # Fix Python syntax typos
        syntax_fixes = {
            "as def ": "async def ",
            "ascontextmanager": "asynccontextmanager",
            "awit ": "await ",
            "awiat": "await"
        }
        for wrong, correct in syntax_fixes.items():
            if wrong in content:
                content = content.replace(wrong, correct)
                fixes_count += 1
        
        # Fix CORS — ensure 5959 is always in allowed origins
        if "main.py" in rel_path and "CORSMiddleware" in content and "5959" not in content:
            content = content.replace(
                '"http://localhost:5173"',
                '"http://localhost:5959", "http://localhost:5173"'
            )
            content = content.replace(
                "'http://localhost:5173'",
                "'http://localhost:5959', 'http://localhost:5173'"
            )
            fixes_count += 1

        # Fix circular import - only strip TOP-LEVEL imports, not indented lazy imports inside functions
        if "from app.services.user_service import" in content and "app/utils/security.py" in rel_path:
            content = re.sub(
                r'^from app\.services\.user_service import [^\n]+\n',
                '# Lazy import moved inside function to prevent circular dependency\n',
                content,
                flags=re.MULTILINE
            )
            fixes_count += 1

        # Ensure security.py has the actual lazy import inside get_current_user
        if "app/utils/security.py" in rel_path and "get_current_user" in content:
            content = content.replace(
                "# Lazy import moved inside function to prevent circular dependency\n",
                ""
            )
            if ("from app.services.user_service import get_user_by_id" not in content
                    and "user = await get_user_by_id(" in content):
                content = content.replace(
                    "    user = await get_user_by_id(",
                    "    from app.services.user_service import get_user_by_id\n    user = await get_user_by_id("
                )
                fixes_count += 1
        
        # Fix deprecated Pydantic v1 PyObjectId validators
        if "__get_validators__" in content and "PyObjectId" in content:
            content = content.replace(
                "    @classmethod\n    def __get_validators__(cls):\n        yield cls.validate\n\n    @classmethod\n    def validate(cls, v, _):\n        if not ObjectId.is_valid(v):\n            raise ValueError(\"Invalid ObjectId\")\n        return ObjectId(v)\n\n    @classmethod\n    def __get_pydantic_json_schema__(cls, field_schema):\n        field_schema.update(type=\"string\")",
                "    @classmethod\n    def __get_pydantic_core_schema__(cls, source_type, handler):\n        from pydantic_core import core_schema\n        return core_schema.union_schema([\n            core_schema.str_schema(),\n            core_schema.is_instance_schema(ObjectId),\n        ], serialization=core_schema.to_string_schema())\n\n    @classmethod\n    def validate(cls, v):\n        if isinstance(v, ObjectId):\n            return v\n        if not ObjectId.is_valid(v):\n            raise ValueError(\"Invalid ObjectId\")\n        return ObjectId(v)"
            )
            fixes_count += 1
        
        # Fix passlib + bcrypt 4.x incompatibility (passlib's detect_wrap_bug uses 72+ byte secret which bcrypt 4.x rejects)
        if "from passlib.context import CryptContext" in content and "pwd_context" in content:
            content = content.replace("from passlib.context import CryptContext\n", "import bcrypt as _bcrypt_lib\n")
            content = re.sub(r'pwd_context\s*=\s*CryptContext\([^\n]+\)\n', '', content)
            content = content.replace(
                "def verify_password(plain_password: str, hashed_password: str) -> bool:\n    return pwd_context.verify(plain_password, hashed_password)",
                "def verify_password(plain_password: str, hashed_password: str) -> bool:\n    pw = plain_password.encode('utf-8')[:72]\n    return _bcrypt_lib.checkpw(pw, hashed_password.encode('utf-8'))"
            )
            content = re.sub(
                r'def get_password_hash\(password: str\) -> str:.*?(?=\ndef |\nasync def )',
                "def get_password_hash(password: str) -> str:\n    pw = password.encode('utf-8')[:72]\n    return _bcrypt_lib.hashpw(pw, _bcrypt_lib.gensalt()).decode('utf-8')\n",
                content,
                flags=re.DOTALL
            )
            fixes_count += 1
        
        # Fix PyObjectId in schemas.py
        if "PyObjectId" in content and rel_path == "app/schemas.py":
            content = content.replace("from app.models import PyObjectId", "")
            content = content.replace(": PyObjectId", ": str")
            content = content.replace("PyObjectId: str", "str")
            fixes_count += 1
        
        # Fix PyObjectId in models.py
        if "PyObjectId" in content and rel_path == "app/models.py":
            content = re.sub(
                r'class PyObjectId\(ObjectId\):.*?(?=\n# ---|\nclass )',
                '',
                content,
                flags=re.DOTALL
            )
            content = content.replace(": PyObjectId", ": str")
            content = content.replace("PyObjectId = Field(", "str = Field(")
            content = content.replace("PyObjectId(", "str(")
            content = content.replace("default_factory=PyObjectId", "default_factory=lambda: str(ObjectId())")
            content = content.replace("arbitrary_types_allowed = True", "")
            content = content.replace("json_encoders = {ObjectId: str}", "json_encoders = {ObjectId: str}")
            fixes_count += 1
        
        # Fix missing ObjectId import
        if "ObjectId" in content and "from bson import ObjectId" not in content:
            if "from datetime import datetime" in content:
                content = content.replace("from datetime import datetime", "from datetime import datetime\nfrom bson import ObjectId")
            elif "import datetime" in content:
                content = content.replace("import datetime", "import datetime\nfrom bson import ObjectId")
            else:
                content = "from bson import ObjectId\n" + content
            fixes_count += 1
        
        # Fix missing uvicorn run command in main.py
        if rel_path == "main.py" and "if __name__" not in content:
            content += '\n\nif __name__ == "__main__":\n    import uvicorn\n    uvicorn.run("main:app", host="0.0.0.0", port=7979, reload=True)\n'
            fixes_count += 1

        # Fix incorrect uvicorn port (should be 7979)
        if rel_path == "main.py" and "uvicorn.run" in content:
            content = re.sub(r'port\s*=\s*\d+', 'port=7979', content)
            content = re.sub(r'uvicorn\.run\("app:create_app"', 'uvicorn.run("main:app"', content)
            fixes_count += 1

        # Fix datetime.now() → datetime.utcnow() (motor stores UTC)
        if "datetime.now()" in content:
            content = content.replace("datetime.now()", "datetime.utcnow()")
            fixes_count += 1

        # Fix wrong bson import path
        if "from bson.objectid import ObjectId" in content:
            content = content.replace("from bson.objectid import ObjectId", "from bson import ObjectId")
            fixes_count += 1

        # Fix missing datetime import when datetime.utcnow() is used
        if "datetime.utcnow()" in content and "from datetime import datetime" not in content and "import datetime" not in content:
            content = "from datetime import datetime\n" + content
            fixes_count += 1

        # Fix motor .to_list() called without length= parameter
        patched = re.sub(r'\.to_list\s*\(\s*\)', '.to_list(length=1000)', content)
        if patched != content:
            content = patched
            fixes_count += 1

        # Fix sync `def` route functions that use `await` — must be `async def`
        def _make_async(m):
            return m.group(0).replace("def ", "async def ", 1)
        patched = re.sub(
            r'^(\s*)def (\w+\s*\([^)]*\)[^:]*:(?:\s*\n(?:(?!\s*def |\s*async def ).*\n)*?.*\bawait\b))',
            _make_async,
            content,
            flags=re.MULTILINE,
        )
        if patched != content:
            content = patched
            fixes_count += 1

        # Fix missing `await` before motor operations assigned directly
        for op in ("find_one", "insert_one", "update_one", "delete_one",
                   "find_one_and_update", "find_one_and_delete", "count_documents"):
            # Only add await if not already present and inside an async context (file has async def)
            if f"async def" in content:
                patched = re.sub(
                    rf'(?<![a-z_])(?<!await )(db\.\w+\.{op}\()',
                    r'await \1',
                    content,
                )
                if patched != content:
                    content = patched
                    fixes_count += 1

        # Fix Pydantic v1 class Config → model_config (pydantic v2)
        if "class Config:" in content and ("BaseSettings" in content or "BaseModel" in content):
            patched = re.sub(
                r'    class Config:\s*\n(\s+env_file\s*=\s*["\']\.env["\']\s*\n)?(\s+case_sensitive\s*=\s*\w+\s*\n)?',
                '    model_config = {"env_file": ".env", "case_sensitive": True}\n',
                content,
            )
            if patched != content:
                content = patched
                fixes_count += 1

        # Fix Pydantic v1 orm_mode → from_attributes (pydantic v2)
        if "orm_mode = True" in content:
            content = content.replace("orm_mode = True", "from_attributes = True")
            fixes_count += 1

        # Fix wrong response: login returning 404 for invalid credentials (must be 401)
        if "auth" in rel_path and "404" in content and "Invalid" in content:
            content = re.sub(
                r'HTTPException\(status_code=404,\s*detail=["\'](?:Invalid|Wrong|Incorrect|User not found)[^"\']*["\']\)',
                'HTTPException(status_code=401, detail="Invalid email or password")',
                content,
            )
            fixes_count += 1

        # Fix main.py: ensure startup/shutdown events use lifespan or on_event
        if rel_path == "main.py" and "connect_db" in content and "@app.on_event" not in content and "lifespan" not in content:
            lifespan = (
                '\nfrom contextlib import asynccontextmanager\n'
                '@asynccontextmanager\nasync def lifespan(app):\n'
                '    await connect_db()\n    yield\n    await disconnect_db()\n'
            )
            content = re.sub(r'(app\s*=\s*FastAPI\([^)]*\))', lifespan + r'\n\1', content, count=1)
            content = re.sub(r'app\s*=\s*FastAPI\(', 'app = FastAPI(lifespan=lifespan, ', content, count=1)
            fixes_count += 1

        if fixes_count > 0:
            self.fixes_applied.append(f"{rel_path}: {fixes_count} fixes")

        return content

    def auto_fix_frontend_file(self, content: str, rel_path: str) -> str:
        """Apply auto-fixes to frontend file content."""
        original_content = content
        fixes_count = 0
        
        # Fix missing Vite proxy configuration
        if rel_path == "vite.config.ts" and "proxy:" not in content:
            content = content.replace(
                "server: {\n    port: 5173,\n  },",
                "server: {\n    port: 5173,\n    proxy: {\n      '/api': {\n        target: 'http://localhost:7979',\n        changeOrigin: true,\n      },\n    },\n  },"
            )
            fixes_count += 1
        
        # Fix incorrect proxy target port
        if rel_path == "vite.config.ts" and "target: 'http://localhost:8000'" in content:
            content = content.replace("target: 'http://localhost:8000'", "target: 'http://localhost:7979'")
            fixes_count += 1
        
        # Fix incorrect proxy target port with double quotes
        if rel_path == "vite.config.ts" and 'target: "http://localhost:8000"' in content:
            content = content.replace('target: "http://localhost:8000"', 'target: "http://localhost:7979"')
            fixes_count += 1
        
        # Fix hardcoded backend URLs in source files — NEVER touch vite.config.ts.
        # vite.config.ts proxy target MUST stay as http://localhost:7979.
        if rel_path != "vite.config.ts":
            content = content.replace("http://localhost:8000/api", "/api")
            content = content.replace("http://localhost:8000", "")
            content = content.replace("'http://localhost:7979/api'", "'/api'")
            content = content.replace('"http://localhost:7979/api"', '"/api"')
            # Do NOT replace bare 'http://localhost:7979' — valid in proxy targets
            if "http://localhost:8000" in original_content:
                fixes_count += 1

        # Repair vite.config.ts if the proxy target was wiped to empty string
        if rel_path == "vite.config.ts":
            if "target: ''" in content or 'target: ""' in content:
                content = content.replace("target: ''", "target: 'http://localhost:7979'")
                content = content.replace('target: ""', "target: 'http://localhost:7979'")
                fixes_count += 1

        # Fix axios baseURL if it's hardcoded to wrong port
        if "baseURL: 'http://localhost:8000'" in content or 'baseURL: "http://localhost:8000"' in content:
            content = content.replace("baseURL: 'http://localhost:8000'", "baseURL: '/api'")
            content = content.replace('baseURL: "http://localhost:8000"', 'baseURL: "/api"')
            fixes_count += 1

        if "baseURL: 'http://localhost:7979'" in content or 'baseURL: "http://localhost:7979"' in content:
            content = content.replace("baseURL: 'http://localhost:7979'", "baseURL: '/api'")
            content = content.replace('baseURL: "http://localhost:7979"', 'baseURL: "/api"')
            fixes_count += 1
        
        # Fix SVG imports used as React components — crashes without vite-plugin-svgr
        if rel_path.endswith((".tsx", ".ts")) and re.search(r'import \w+ from ["\'][^"\']+\.svg(?:\?react)?["\']', content):
            svg_vars = re.findall(r'import (\w+) from ["\'][^"\']+\.svg(?:\?react)?["\']', content)
            content = re.sub(r'import \w+ from ["\'][^"\']+\.svg(?:\?react)?["\'];?\n?', '', content)
            for var in svg_vars:
                content = re.sub(rf'<{var}(\s[^>]*)?\s*/>', f'<span className="brand-logo">{var}</span>', content)
                content = re.sub(rf'<{var}(\s[^>]*)?>.*?</{var}>', f'<span className="brand-logo">{var}</span>', content, flags=re.DOTALL)
            fixes_count += 1

        # Fix TypeScript strict mode in tsconfig.json
        if rel_path == "tsconfig.json" and '"strict": false' in content:
            content = content.replace('"strict": false', '"strict": true')
            fixes_count += 1
        
        # Fix class components to functional components (basic pattern)
        if rel_path.endswith(".tsx") and "class " in content and "extends React.Component" in content:
            # This is a basic fix - complex conversions need manual review
            content = content.replace("extends React.Component", "// TODO: Convert to functional component")
            fixes_count += 1
        
        # Fix missing React import
        if rel_path.endswith(".tsx") and "import React" not in content and "jsx" in content.lower():
            content = "import React from 'react'\n" + content
            fixes_count += 1
        
        # Auto-fix unsafe .split() calls that crash when the value is null/undefined.
        # Pattern: someExpr.split(  →  (someExpr ?? "").split(
        # We only target identifiers and property chains (not already-guarded calls).
        if rel_path.endswith((".ts", ".tsx")) and ".split(" in content:
            # Replace `identifier.split(` with `(identifier ?? "").split(` when not already guarded
            content = re.sub(
                r'(?<![?!])\b((?:[a-zA-Z_$][a-zA-Z0-9_$]*\.)+[a-zA-Z_$][a-zA-Z0-9_$]*)\.split\(',
                r'(\1 ?? "").split(',
                content,
            )
            if content != original_content:
                fixes_count += 1

        # Note: missing npm dependency injection is handled upstream by
        # core.validation.dependency_injector.fix_flat_files(), which runs
        # the full import-scanner before files are saved. No blind injection here.
        
        # Fix class= → className= in JSX (most common LLM mistake)
        if rel_path.endswith((".tsx", ".jsx")):
            patched = re.sub(r'(?<!\w)class=(["\'{])', r'className=\1', content)
            if patched != content:
                content = patched
                fixes_count += 1

        # Fix for= → htmlFor= in JSX labels
        if rel_path.endswith((".tsx", ".jsx")):
            patched = re.sub(r'(?<!\w)for=(["\'{])', r'htmlFor=\1', content)
            if patched != content:
                content = patched
                fixes_count += 1

        # Fix duplicate /api prefix: api.get('/api/tasks') → api.get('/tasks')
        if rel_path.endswith((".ts", ".tsx")):
            patched = re.sub(
                r'(api\s*\.\s*(?:get|post|put|patch|delete)\s*\(\s*["`\'])\s*/api/',
                r'\1/',
                content,
            )
            if patched != content:
                content = patched
                fixes_count += 1

        # Fix missing React hooks imports comprehensively
        if rel_path.endswith((".tsx", ".ts")):
            hooks = ["useState", "useEffect", "useCallback", "useMemo", "useRef",
                     "useContext", "useReducer", "useLayoutEffect", "useId"]
            needed = [h for h in hooks if h in content]
            if needed:
                # Find existing react import
                react_import = re.search(
                    r"import\s+(?:React\s*,\s*)?\{([^}]+)\}\s+from\s+'react'",
                    content,
                )
                if react_import:
                    existing = [x.strip() for x in react_import.group(1).split(",")]
                    missing_hooks = [h for h in needed if h not in existing]
                    if missing_hooks:
                        new_imports = ", ".join(sorted(set(existing + missing_hooks)))
                        content = content.replace(
                            react_import.group(0),
                            f"import {{ {new_imports} }} from 'react'",
                        )
                        fixes_count += 1
                elif "import React from 'react'" in content:
                    hooks_str = ", ".join(needed)
                    content = content.replace(
                        "import React from 'react'",
                        f"import React, {{ {hooks_str} }} from 'react'",
                    )
                    fixes_count += 1
                else:
                    # No react import at all — add one
                    hooks_str = ", ".join(needed)
                    content = f"import {{ {hooks_str} }} from 'react'\n" + content
                    fixes_count += 1

        # Fix missing router imports (useNavigate, Link, NavLink, Routes, Route, Navigate)
        if rel_path.endswith((".tsx", ".ts")):
            router_hooks = {
                "useNavigate": "useNavigate",
                "useParams": "useParams",
                "useLocation": "useLocation",
                "<Link ": "Link",
                "<NavLink ": "NavLink",
                "<Routes>": "Routes",
                "<Route ": "Route",
                "<Navigate ": "Navigate",
                "<Outlet": "Outlet",
            }
            needed_router = []
            for trigger, symbol in router_hooks.items():
                if trigger in content:
                    needed_router.append(symbol)
            if needed_router:
                rrd_import = re.search(
                    r"import\s*\{([^}]+)\}\s*from\s*'react-router-dom'",
                    content,
                )
                if rrd_import:
                    existing = [x.strip() for x in rrd_import.group(1).split(",")]
                    missing = [s for s in needed_router if s not in existing]
                    if missing:
                        new_str = ", ".join(sorted(set(existing + missing)))
                        content = content.replace(
                            rrd_import.group(0),
                            f"import {{ {new_str} }} from 'react-router-dom'",
                        )
                        fixes_count += 1
                else:
                    syms = ", ".join(sorted(set(needed_router)))
                    content = f"import {{ {syms} }} from 'react-router-dom'\n" + content
                    fixes_count += 1

        # Fix missing key prop in .map() JSX — add key={item.id ?? item._id ?? idx}
        if rel_path.endswith((".tsx", ".jsx")) and ".map(" in content:
            def _add_key(m: re.Match) -> str:
                tag, attrs, var, idx = m.group(1), m.group(2), m.group(3), m.group(4)
                if "key=" in attrs:
                    return m.group(0)
                key_val = f"{var}.id ?? {var}._id ?? {idx or 'i'}"
                return f"<{tag} key={{{key_val}}}{attrs}"
            patched = re.sub(
                r'\.map\(\s*\(\s*(\w+)(?:\s*,\s*(\w+))?\s*\)[^=]*?=>\s*(?:\(?\s*)?'
                r'<([A-Za-z][A-Za-z0-9]*)((?:\s+(?!key=)[a-zA-Z][^>]*?)?)',
                lambda m: (
                    m.group(0) if "key=" in m.group(0) else
                    m.group(0).replace(
                        f"<{m.group(3)}{m.group(4)}",
                        f"<{m.group(3)} key={{{m.group(1)}.id ?? {m.group(1)}._id ?? {m.group(2) or 'i'}}}{m.group(4)}",
                        1,
                    )
                ),
                content,
            )
            if patched != content:
                content = patched
                fixes_count += 1

        # Fix missing export default for component files
        if (rel_path.endswith(".tsx") and
                "export default" not in content and
                "export default function" not in content):
            # Find last function definition that looks like a component (PascalCase)
            comp_match = re.search(r'function\s+([A-Z][A-Za-z0-9]+)\s*\(', content)
            if comp_match:
                comp_name = comp_match.group(1)
                content += f"\n\nexport default {comp_name}\n"
                fixes_count += 1

        # Fix missing useState/useEffect imports (legacy fallback)
        if rel_path.endswith(".tsx"):
            if "useState" in content and "useState" not in content[:content.find("useState")]:
                pass  # Already handled above
            if "useEffect" in content and "useEffect" not in content[:content.find("useEffect")]:
                pass  # Already handled above

        if fixes_count > 0:
            self.fixes_applied.append(f"{rel_path}: {fixes_count} fixes")

        return content

    def validate_python_syntax(self, content: str) -> tuple[bool, str]:
        """Validate Python syntax and return (is_valid, error_message)."""
        try:
            compile(content, '<string>', 'exec')
            return True, ""
        except SyntaxError as e:
            return False, f"Python syntax error: {e}"

    def auto_fix_main_py_routers(self, backend_path: Path) -> int:
        """Scan all route files and ensure main.py registers them. Returns count of fixes."""
        main_py = backend_path / "main.py"
        if not main_py.exists():
            return 0
        routes_dir = backend_path / "app" / "routes"
        if not routes_dir.exists():
            return 0

        main_content = main_py.read_text(encoding="utf-8")
        fixes = 0

        for route_file in routes_dir.glob("*.py"):
            if route_file.name in ("__init__.py",):
                continue
            module_name = route_file.stem  # e.g. "tasks"
            # Check if this router is already registered
            if f"routes.{module_name}" in main_content or f"from app.routes import {module_name}" in main_content:
                continue
            if f'include_router({module_name}' in main_content:
                continue

            # Add import + include_router
            import_line = f"from app.routes import {module_name}\n"
            router_line = f'app.include_router({module_name}.router, prefix="/api/{module_name}s", tags=["{module_name}s"])\n'

            # Insert import after last existing route import
            if "from app.routes import" in main_content:
                last_route_import = max(
                    (m.end() for m in re.finditer(r'from app\.routes import \w+\n', main_content)),
                    default=None,
                )
                if last_route_import:
                    main_content = main_content[:last_route_import] + import_line + main_content[last_route_import:]
            else:
                # Add import near top
                main_content = import_line + main_content

            # Insert include_router after last existing include_router call
            last_router = max(
                (m.end() for m in re.finditer(r'app\.include_router\([^\n]+\)\n', main_content)),
                default=None,
            )
            if last_router:
                main_content = main_content[:last_router] + router_line + main_content[last_router:]
            else:
                # Append before the health check or at end
                if 'async def health' in main_content:
                    main_content = re.sub(
                        r'(@app\.get\("/health"\))',
                        router_line + r'\n\1',
                        main_content,
                        count=1,
                    )
                else:
                    main_content += "\n" + router_line

            fixes += 1
            if self.verbose:
                print(f"[Debugger] Auto-registered router: {module_name}")

        if fixes:
            main_py.write_text(main_content, encoding="utf-8")
            self.fixes_applied.append(f"main.py: registered {fixes} missing router(s)")

        return fixes

    def fix_project_backend(self, backend_path: Path) -> dict:
        """Fix all backend files in a project and return fix summary."""
        fix_summary = {
            "files_processed": 0,
            "files_fixed": 0,
            "errors_fixed": [],
            "syntax_errors": []
        }
        
        if not backend_path.exists():
            fix_summary["errors_fixed"].append("Backend path does not exist")
            return fix_summary
        
        # Process all Python files in backend
        for py_file in backend_path.rglob("*.py"):
            try:
                rel_path = str(py_file.relative_to(backend_path))
                original_content = py_file.read_text(encoding="utf-8")
                
                # Apply auto-fixes
                fixed_content = self.auto_fix_backend_file(original_content, rel_path)
                
                # Validate syntax after fixes
                is_valid, syntax_error = self.validate_python_syntax(fixed_content)
                
                if not is_valid:
                    fix_summary["syntax_errors"].append(f"{rel_path}: {syntax_error}")
                    self.errors_found.append(f"Syntax error in {rel_path}: {syntax_error}")
                    continue  # Don't write files with syntax errors
                
                # Write fixed content if changed
                if fixed_content != original_content:
                    py_file.write_text(fixed_content, encoding="utf-8")
                    fix_summary["files_fixed"] += 1
                    fix_summary["errors_fixed"].append(f"Fixed {rel_path}")
                    if self.verbose:
                        print(f"[Debugger] Fixed: {rel_path}")
                
                fix_summary["files_processed"] += 1
                
            except Exception as e:
                error_msg = f"Error processing {py_file}: {str(e)}"
                fix_summary["errors_fixed"].append(error_msg)
                self.errors_found.append(error_msg)
        
        # Auto-register any missing entity routers in main.py
        router_fixes = self.auto_fix_main_py_routers(backend_path)
        if router_fixes:
            fix_summary["files_fixed"] += 1
            fix_summary["errors_fixed"].append(f"main.py: registered {router_fixes} missing router(s)")

        return fix_summary

    def _ensure_critical_frontend_files(self, frontend_path: Path) -> list[str]:
        """Create minimal stubs for any critical frontend files that are missing."""
        created = []
        src = frontend_path / "src"
        src.mkdir(parents=True, exist_ok=True)

        _stubs: dict[str, str] = {
            "src/main.tsx": (
                "import React from 'react'\n"
                "import ReactDOM from 'react-dom/client'\n"
                "import { BrowserRouter } from 'react-router-dom'\n"
                "import App from './App'\n"
                "import './index.css'\n\n"
                "ReactDOM.createRoot(document.getElementById('root')!).render(\n"
                "  <React.StrictMode><BrowserRouter><App /></BrowserRouter></React.StrictMode>\n"
                ")\n"
            ),
            "src/App.tsx": (
                "import { Routes, Route, Navigate } from 'react-router-dom'\n\n"
                "export default function App() {\n"
                "  return (\n"
                "    <Routes>\n"
                "      <Route path='/' element={<Navigate to='/dashboard' replace />} />\n"
                "      <Route path='/dashboard' element={<div>Dashboard</div>} />\n"
                "    </Routes>\n"
                "  )\n"
                "}\n"
            ),
            "src/index.css": (
                ":root { --color-primary: #6366f1; --color-bg: #0f172a; --color-surface: #1e293b; "
                "--color-text: #f8fafc; --color-text-muted: #94a3b8; --color-border: #334155; "
                "--radius-md: 8px; --shadow-md: 0 4px 16px rgba(0,0,0,0.3); }\n"
                "* { box-sizing: border-box; margin: 0; padding: 0; }\n"
                "body { font-family: system-ui, sans-serif; background: var(--color-bg); "
                "color: var(--color-text); min-height: 100vh; }\n"
            ),
            "src/types/index.ts": (
                "export interface User {\n  id: string\n  email: string\n  name: string\n  createdAt: string\n}\n\n"
                "export interface AuthResponse {\n  access_token: string\n  token_type: string\n  user: User\n}\n"
            ),
            "src/services/api.ts": (
                "import axios from 'axios'\n\n"
                "const api = axios.create({ baseURL: '/api', timeout: 15000 })\n"
                "const STORAGE_KEY = 'auth-storage-v2'\n\n"
                "api.interceptors.request.use((config) => {\n"
                "  try {\n"
                "    const raw = localStorage.getItem(STORAGE_KEY)\n"
                "    if (raw) { const token = JSON.parse(raw)?.state?.token; if (token) config.headers.Authorization = `Bearer ${token}` }\n"
                "  } catch {}\n"
                "  return config\n"
                "})\n"
                "api.interceptors.response.use((r) => r, (err) => {\n"
                "  if (err.response?.status === 401) { localStorage.removeItem(STORAGE_KEY); window.location.href = '/login' }\n"
                "  return Promise.reject(err)\n"
                "})\n\n"
                "export default api\n"
            ),
            "src/stores/authStore.ts": (
                "import { create } from 'zustand'\nimport { persist } from 'zustand/middleware'\n"
                "import { User } from '../types'\nimport api from '../services/api'\n\n"
                "interface AuthState {\n"
                "  user: User | null; token: string | null; isAuthenticated: boolean\n"
                "  isLoading: boolean; error: string | null\n"
                "  login: (email: string, password: string) => Promise<void>\n"
                "  logout: () => void; fetchMe: () => Promise<void>\n"
                "}\n\n"
                "export const useAuthStore = create<AuthState>()(persist(\n"
                "  (set) => ({\n"
                "    user: null, token: null, isAuthenticated: false, isLoading: false, error: null,\n"
                "    login: async (email, password) => {\n"
                "      set({ isLoading: true, error: null })\n"
                "      try {\n"
                "        const { data } = await api.post('/auth/login', { email, password })\n"
                "        set({ user: data.user, token: data.access_token, isAuthenticated: true, isLoading: false })\n"
                "      } catch (e: any) { set({ error: e.response?.data?.detail || 'Login failed', isLoading: false }) }\n"
                "    },\n"
                "    logout: () => set({ user: null, token: null, isAuthenticated: false }),\n"
                "    fetchMe: async () => {\n"
                "      try { const { data } = await api.get('/auth/me'); set({ user: data, isAuthenticated: true }) }\n"
                "      catch { set({ isAuthenticated: false }) }\n"
                "    },\n"
                "  }),\n"
                "  { name: 'auth-storage-v2', partialize: (s) => ({ token: s.token, user: s.user, isAuthenticated: s.isAuthenticated }) }\n"
                "))\n"
            ),
            "src/components/common/LoadingSpinner.tsx": (
                "export default function LoadingSpinner() {\n"
                "  return <div style={{display:'flex',justifyContent:'center',padding:'2rem'}}>"
                "<div className='spinner' /></div>\n}\n"
            ),
            "src/components/common/EmptyState.tsx": (
                "interface EmptyStateProps { title?: string; description?: string; action?: React.ReactNode }\n"
                "export default function EmptyState({ title = 'Nothing here yet', description, action }: EmptyStateProps) {\n"
                "  return (\n"
                "    <div className='empty-state'>\n"
                "      <p className='empty-title'>{title}</p>\n"
                "      {description && <p className='empty-description'>{description}</p>}\n"
                "      {action && <div className='empty-action'>{action}</div>}\n"
                "    </div>\n"
                "  )\n"
                "}\n"
            ),
        }

        for rel, stub_content in _stubs.items():
            target = frontend_path / rel.replace("/", "\\")
            if not target.exists():
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(stub_content, encoding="utf-8")
                created.append(rel)
                if self.verbose:
                    print(f"[Debugger] Created missing stub: {rel}")

        return created

    def fix_project_frontend(self, frontend_path: Path) -> dict:
        """Fix all frontend files in a project and return fix summary."""
        fix_summary = {
            "files_processed": 0,
            "files_fixed": 0,
            "errors": []
        }
        
        package_json_modified = False
        
        try:
            for file in frontend_path.rglob("*"):
                if file.is_file() and file.suffix in [".ts", ".tsx", ".json", ".css"]:
                    try:
                        rel_path = str(file.relative_to(frontend_path))
                        content = file.read_text(encoding="utf-8")
                        original_content = content
                        
                        fixed_content = self.auto_fix_frontend_file(content, rel_path)
                        
                        if fixed_content != original_content:
                            file.write_text(fixed_content, encoding="utf-8")
                            fix_summary["files_fixed"] += 1
                            
                            # Check if package.json was modified
                            if rel_path == "package.json":
                                package_json_modified = True
                        
                        fix_summary["files_processed"] += 1
                    except Exception as e:
                        fix_summary["errors"].append(f"Error fixing {file.relative_to(frontend_path)}: {str(e)}")
        except Exception as e:
            fix_summary["errors"].append(f"Error fixing frontend: {str(e)}")
        
        # Ensure all critical files exist (create stubs for missing ones)
        stubs_created = self._ensure_critical_frontend_files(frontend_path)
        if stubs_created:
            fix_summary["files_fixed"] += len(stubs_created)
            fix_summary.setdefault("stubs_created", stubs_created)

        return fix_summary
    def fix_entire_project(self, project_path: Path) -> dict:
        """Fix both frontend and backend of a project."""
        backend_path = project_path / "backend"
        frontend_path = project_path / "frontend"
        
        if self.verbose:
            print(f"[Debugger] Starting project fix: {project_path}")
        
        backend_summary = self.fix_project_backend(backend_path)
        frontend_summary = self.fix_project_frontend(frontend_path)
        
        # Validate after fixes
        backend_errors = self.validate_backend_code(backend_path)
        frontend_errors = self.validate_frontend_code(frontend_path)
        
        # Add validation errors to errors_found
        for error in backend_errors:
            self.errors_found.append(f"Backend validation: {error}")
        for error in frontend_errors:
            self.errors_found.append(f"Frontend validation: {error}")
        
        result = {
            "backend": backend_summary,
            "frontend": frontend_summary,
            "backend_validation_errors": backend_errors,
            "frontend_validation_errors": frontend_errors,
            "total_files_processed": backend_summary["files_processed"] + frontend_summary["files_processed"],
            "total_files_fixed": backend_summary["files_fixed"] + frontend_summary["files_fixed"],
            "fixes_applied": self.fixes_applied,
            "errors_found": self.errors_found
        }
        
        if self.verbose:
            print(f"[Debugger] Project fix complete:")
            print(f"  - Files processed: {result['total_files_processed']}")
            print(f"  - Files fixed: {result['total_files_fixed']}")
            print(f"  - Validation errors: {len(backend_errors) + len(frontend_errors)}")
        
        return result

    def analyze_performance(self, project_path: Path) -> Dict[str, Any]:
        """Analyze project for performance issues and optimizations."""
        metrics = {
            "total_files": 0,
            "python_files": 0,
            "typescript_files": 0,
            "large_files": [],
            "complex_functions": [],
            "optimization_suggestions": []
        }
        
        try:
            # Count files and identify large files
            for file in project_path.rglob("*"):
                if file.is_file():
                    metrics["total_files"] += 1
                    try:
                        size = file.stat().st_size
                        if size > 100000:  # Files larger than 100KB
                            metrics["large_files"].append({
                                "path": str(file.relative_to(project_path)),
                                "size_kb": size // 1024
                            })
                    except Exception:
                        pass
                    
                    if file.suffix == ".py":
                        metrics["python_files"] += 1
                    elif file.suffix in [".ts", ".tsx"]:
                        metrics["typescript_files"] += 1
            
            # Check for complex functions (simplified heuristic)
            for py_file in project_path.rglob("*.py"):
                try:
                    content = py_file.read_text(encoding="utf-8")
                    lines = content.split("\n")
                    # Count function definitions
                    func_count = content.count("def ")
                    if func_count > 20:
                        metrics["complex_functions"].append({
                            "path": str(py_file.relative_to(project_path)),
                            "function_count": func_count
                        })
                except Exception:
                    pass
            
            # Optimization suggestions
            if metrics["large_files"]:
                metrics["optimization_suggestions"].append("Consider splitting large files into smaller modules")
            if metrics["complex_functions"]:
                metrics["optimization_suggestions"].append("Consider breaking down complex functions into smaller, testable units")
            
            self.performance_metrics = metrics
            
            if self.verbose:
                print(f"[Debugger] Performance analysis:")
                print(f"  - Total files: {metrics['total_files']}")
                print(f"  - Python files: {metrics['python_files']}")
                print(f"  - TypeScript files: {metrics['typescript_files']}")
                print(f"  - Large files: {len(metrics['large_files'])}")
                print(f"  - Optimization suggestions: {len(metrics['optimization_suggestions'])}")
            
        except Exception as e:
            if self.verbose:
                print(f"[Debugger] Performance analysis error: {e}")
        
        return metrics

    def scan_security_vulnerabilities(self, project_path: Path) -> List[str]:
        """Scan project for common security vulnerabilities."""
        vulnerabilities = []
        
        try:
            # Check for hardcoded secrets in backend
            for py_file in project_path.rglob("*.py"):
                try:
                    content = py_file.read_text(encoding="utf-8")
                    # Check for common secret patterns
                    if "api_key" in content.lower() and "=" in content:
                        vulnerabilities.append(f"Potential API key in {py_file.relative_to(project_path)}")
                    if "password" in content.lower() and "=" in content and "hash" not in content.lower():
                        vulnerabilities.append(f"Potential hardcoded password in {py_file.relative_to(project_path)}")
                    if "secret" in content.lower() and "=" in content and "os.environ" not in content:
                        vulnerabilities.append(f"Potential hardcoded secret in {py_file.relative_to(project_path)}")
                except Exception:
                    pass
            
            # Check for insecure dependencies (simplified)
            req_file = project_path / "backend" / "requirements.txt"
            if req_file.exists():
                content = req_file.read_text(encoding="utf-8")
                # Check for known vulnerable versions (simplified check)
                if "django" in content.lower():
                    vulnerabilities.append("Django detected - ensure latest version is used")
                if "flask" in content.lower():
                    vulnerabilities.append("Flask detected - ensure latest version is used")
            
            # Check for CORS misconfiguration
            main_file = project_path / "backend" / "main.py"
            if main_file.exists():
                content = main_file.read_text(encoding="utf-8")
                if "allow_origins" in content and "*" in content:
                    vulnerabilities.append("CORS configured with wildcard origin - this is insecure for production")
            
            self.security_issues = vulnerabilities
            
            if self.verbose:
                print(f"[Debugger] Security scan found {len(vulnerabilities)} potential vulnerabilities")
                for vuln in vulnerabilities:
                    print(f"  - {vuln}")
            
        except Exception as e:
            if self.verbose:
                print(f"[Debugger] Security scan error: {e}")
        
        return vulnerabilities
